// <auto-generated />
namespace BlogSitesi.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PhoneNumberTypeChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhoneNumberTypeChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202001052249448_PhoneNumberTypeChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
